# Generated by Django 5.1.4 on 2025-01-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profeta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Diccionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(blank=True, max_length=100, null=True)),
                ('definicion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctrina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('maintexto', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('st_am', models.IntegerField()),
                ('end_am', models.IntegerField()),
                ('st_pm', models.IntegerField()),
                ('end_pm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('verso_start', models.IntegerField()),
                ('verso_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doct_verso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verso', models.IntegerField(blank=True, null=True)),
                ('orden_v', models.IntegerField(blank=True, null=True)),
                ('versofk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rv60app.doctrina')),
            ],
        ),
        migrations.CreateModel(
            name='Doct_texto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('orden_t', models.IntegerField(blank=True, null=True)),
                ('textofk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rv60app.doctrina')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=150, null=True)),
                ('libro_en', models.CharField(blank=True, max_length=100, null=True)),
                ('libro_es', models.CharField(blank=True, max_length=100, null=True)),
                ('temaprincipal', models.CharField(blank=True, max_length=500, null=True)),
                ('textos', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.CharField(blank=True, max_length=15, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rv60app.autor')),
                ('divisiones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rv60app.division')),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caps_de_libros', models.IntegerField(blank=True, null=True)),
                ('libros', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rv60app.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Versiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('capitulos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rv60app.capitulo')),
            ],
        ),
    ]
