# Generated by Django 5.1.4 on 2025-01-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rv60app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doct_texto',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctrina',
            name='maintexto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
