# Generated by Django 5.1.4 on 2025-01-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rv60app', '0002_alter_doct_texto_texto_alter_doctrina_maintexto'),
    ]

    operations = [
        migrations.AddField(
            model_name='doct_texto',
            name='orden_t',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doct_verso',
            name='orden_v',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
